### ISSUE TITLE
[BUG] Nationality not needed

### ISSUE THREAD

**Issue by TonybynMp4** [qbcore-framework/qb-multicharacter#148]
If you write something in the nationality then delete what you wrote you'll be able to bypass the error message

Also if you have 6 or more slots before clicking on any slot the 6th slot will be cut out
![image](https://user-images.githubusercontent.com/97451137/187792984-79424809-1fec-4374-b4eb-10b79d8737f3.png)
it's 'normal' since the buttons would be over those but it looks kinda weird
![image](https://user-images.githubusercontent.com/97451137/187793003-a9105df7-05ce-4434-aec5-5d5cc53536ea.png)

**Comment by jnccloud** [comment]
I think the intention here is that if you have more than 5 slots, you're going to be scrolling anyway, which has traditionally been possible using the middle wheel when hovering over the slots. On the matter of nationality, I've considered adding a country selection because I'm getting tired of seeing the nationality being inappropriately completed with 'White' or 'San Andreas'. Perhaps an option for input, a dropdown of real life countries with lore added (if there is any).

**Comment by tom-osborne** [comment]
Fixed in #151
