### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by YouNgWINZy** [qbcore-framework/qb-multicharacter#241]
![image](https://github.com/qbcore-framework/qb-multicharacter/assets/150534628/b0c87096-4e97-4dcc-bc70-7b530864c4ce)

**Comment by Dude495** [comment]
Any resolution to this issue? Seems to be going on for months and no one has a fix.

**Comment by ChristianBDev** [comment]
@Dude495 follow the guidelines  

**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Use this item '....' (item's name from shared.lua if applicable)
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**
Add any other context about the problem here.
