### ISSUE TITLE
Character delete issue

### ISSUE THREAD

**Issue by fredpinet** [qbcore-framework/qb-multicharacter#30]
Intermitent Issue ;

When deleting a character, the UI is not updating ; I've checked the database and the information is deleted so it's really an update/refresh issue I believe. If you try to delete the character that still shows, qb-core kicks player for exploit.

Also tested with multiple characters, if you have say 3 characters, delete one, bug happens ; delete another one, the first deleted character disappears.

Edit : In order to reproduce the issue I cleared cache on both server and my client.

Attached video includes the database refresh, and the issue occuring while deleting multiple characters ;

https://user-images.githubusercontent.com/76604912/131558277-cf6223cd-5f4d-456c-931a-cc08156ace61.mp4

**Comment by IdrisDose** [comment]
I'm currently receiving this same error after the update, I'm looking into that particular issue today, if I find out the core reason I'll post a PR :) (unless someone else gets to it first :D )

**Comment by am3nd01m** [comment]
I just went trought the same issue.

**Comment by bosskitz** [comment]
I had this same issue however, since I have changed the way how new life works in the city, this has been by passed.
ATM, when a player is dead (isdead) = true, and player holds E, it will trigger multicharacter delete character and for some reason, whenever I try to manually delete a character, UI refreshes and shows the "Create Character"...
