### ISSUE TITLE
[Sugestion] Nationality Dropdown

### ISSUE THREAD

**Issue by am3nd01m** [qbcore-framework/qb-multicharacter#37]
Hey, can we get a dropdown menu to choose nationality?

**Comment by jnccloud** [comment]
IMO this would be a bit awkward because many servers wouldn't want to limit the originality of their characters and given the current priority to bug fixes over enhancements, I think this one would be easy to pull of yourself if you want to try my idea below. It's quick and dirty, but you could edit [html/index.html](https://github.com/qbcore-framework/qb-multicharacter/blob/main/html/index.html#L59) line 59 and replace the _nationality_ input with a select similar to the _gender_ select.

So, instead of:

`<input type="text" id="nationality" placeholder="Nationality" class="char-reg-input">`

You could use something like:

```
<select name="nationality">
    <option value="American" selected>American</option>
    <option value="Canadian">Canadian</option>
    <option value="Ukranian">Ukranian</option>
</select>
```
You'd probably also need to edit [html/script.js](https://github.com/qbcore-framework/qb-multicharacter/blob/main/html/script.js#L206) line 206 and change:

`let nationality= escapeHtml($('#nationality').val())` to `let nationality= escapeHtml($('select[name=nationality]').val())`

You add a new `<option .../>` for each nationality you want in your server. You could also store a server-sided table with these details to enforce some type of compliance and validation with the dropdown box, but that would require actual development instead of a one-off customization for this in the HTML file.  

In my personal opinion, there are so many nationalities possible that you'll need to add a pretty hefty list to include all of them, so this might end up being more of a headache to manage in the long run - but at least nothing in the framework relies on it to match a specific value. Hope this helps solve your problem!
